// Test  if the api is working
GET http://localhost:4000/v1/test

###

POST http://localhost:4000/v1/auth/register
content-type: application/json

{
  "username": "test",
  "password": "testagaefad1"
}

###

POST http://localhost:4000/v1/auth/login
content-type: application/json

{
  "username": "test",
  "password": "testagaefad1"
}
