import Lock from "../Lock.js";

export default Lock({
  DISCONNECTED: `DISCONNECTED`,
  CONNECTED: `CONNECTED`,
  CONNECTING: `CONNECTING`,
  DISCONNECTING: `DISCONNECTING`,
  UNINITIALIZED: `UNINITIALIZED`,
  UNKNOWN: `UNKNOWN`,
});
