openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://localhost:4000/v1
paths:
  /:
    get:
      summary: check if server is working
      tags: [operation]
      responses:
        '200':
          content:
            application/json:
              type: object
  /data/{_id}:
    get:
      summary: get json data of entry
      tags:
        - data
      parameters:
        - name: _id
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string

      responses:
        '200':
          description: single json
          content:
            application/json:
              type: object
        '400':
          description: not found
  /data:
    put:
      # TODO someone fix this lmao
      summary: puts a new json entry
      tags: [data]
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true

      requestBody:
        description: the data to upload
        content:
            application/json:
              type: object

#   /pets:
#     get:
#       summary: List all pets
#       operationId: listPets
#       tags:
#         - pets
#       parameters:
#         - name: limit
#           in: query
#           description: How many items to return at one time (max 100)
#           required: false
#           schema:
#             type: integer
#             format: int32
#       responses:
#         '200':
#           description: A paged array of pets
#           headers:
#             x-next:
#               description: A link to the next page of responses
#               schema:
#                 type: string
#           content:
#             application/json:    
#               schema:
#                 $ref: "#/components/schemas/Pets"
#         default:
#           description: unexpected error
#           content:
#             application/json:
#               schema:
#                 $ref: "#/components/schemas/Error"
#     post:
#       summary: Create a pet
#       operationId: createPets
#       tags:
#         - pets
#       responses:
#         '201':
#           description: Null response
#         default:
#           description: unexpected error
#           content:
#             application/json:
#               schema:
#                 $ref: "#/components/schemas/Error"
#   /pets/{petId}:
#     get:
#       summary: Info for a specific pet
#       operationId: showPetById
#       tags:
#         - pets
#       parameters:
#         - name: petId
#           in: path
#           required: true
#           description: The id of the pet to retrieve
#           schema:
#             type: string
#       responses:
#         '200':
#           description: Expected response to a valid request
#           content:
#             application/json:
#               schema:
#                 $ref: "#/components/schemas/Pet"
#         default:
#           description: unexpected error
#           content:
#             application/json:
#               schema:
#                 $ref: "#/components/schemas/Error"
# components:
#   schemas:
#     Pet:
#       type: object
#       required:
#         - id
#         - name
#       properties:
#         id:
#           type: integer
#           format: int64
#         name:
#           type: string
#         tag:
#           type: string
#     Pets:
#       type: array
#       items:
#         $ref: "#/components/schemas/Pet"
#     Error:
#       type: object
#       required:
#         - code
#         - message
#       properties:
#         code:
#           type: integer
#           format: int32
#         message:
#           type: string