name: CI
on: ["push"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: fetch heads and origin head
        run: git fetch origin main && git fetch origin HEAD && git remote set-head origin main

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: npm ci
        run: npm ci

      - name: run lint
        uses: wearerequired/lint-action@v1.7.0
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint: true
          auto_fix: true
      
      - name: setup test
        run: echo "" > .test.env

      - name: initiate mongo
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.4.2
      
      - name: Load mongo
        run: npm run mongoreset -- mongodb://127.0.0.1:27017/database-test

      - name: initialize with default configs
        run: npm run setup
        env:
          PORT: 4000

      - name: run scripts (nothing should error)
        run: >
          npm run help:env &&
          npm run benchmark &&
          npm run mongodump mongodb://127.0.0.1:27017/database-test

      - name: run 0 config
        run: npm test

      - name: run locov
        run: npm run locov
        env:
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          MONGODB_URL: mongodb://127.0.0.1:27017/database-test
          STEM_INFORMATION_URL: mongodb://127.0.0.1:27017/information-test
          PORT: 4000
          LOGGING_ABSOLUTE: "true"

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
  sandbox-deploy:
    needs: build
    runs-on: self-hosted
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: fetch heads and origin head
        run: git fetch origin main && git fetch origin HEAD && git remote set-head origin main
      - run: npm ci --production
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          PUPPETEER_EXECUTABLE_PATH: which chromium
      - run: npm i --no-save typescript cpy-cli
      - run: npm run build 
      - run: npm run setup
      - run: touch .env
      - run: echo "MONGODB_URL=mongodb://127.0.0.1:27017/stem-backend-db-test" >> .env
      - run: echo "CONNECTIONS=\"mongo,discordgql\"" >> .env
      - run: echo "DISCORD_BOT_TOKEN=${{ secrets.SANDBOX_DISCORD_BOT_TOKEN }}" >> .discordbot.env
      - run: pm2 restart 0

