name: PRCI
on: ["pull_request"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: fetch head and set head
        run: git fetch -a

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: yarn install --frozen-lockfile
        run: yarn install --frozen-lockfile

      - name: run lint
        uses: wearerequired/lint-action@v1.7.0
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint: true
          auto_fix: true
      
      - name: setup test
        run: echo "" > .test.env

      - name: initiate mongo
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.4.2
      
      - name: Load mongo
        run: npm run mongoreset -- mongodb://127.0.0.1:27017/database-test

      - name: initialize with default configs
        run: npm run setup
        env:
          PORT: 4000

      - name: run scripts (nothing should error)
        run: >
          npm run help:env &&
          npm run benchmark &&
          npm run mongodump mongodb://127.0.0.1:27017/database-test

      - name: run 0 config
        run: npm test

      - name: run locov
        run: npm run locov
        env:
          MONGODB_URL: mongodb://127.0.0.1:27017/database-test
          PORT: 4000
          LOGGING_ABSOLUTE: "true"

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
